package xyz.the_dodo.bot.Functions.misc;

import xyz.the_dodo.bot.Functions.IFunction;
import xyz.the_dodo.bot.types.MessageParams;
import xyz.the_dodo.bot.utils.RandomGen;

public class CopyPasta extends IFunction
{
	String[] copypastas = {
			"DO IT, just DO IT! Don’t let your dreams be dreams. Yesterday, you said tomorrow. So just. DO IT! Make. your dreams. COME TRUE! Just… do it! Some people dream of success, while you’re gonna wake up and work HARD at it! NOTHING IS IMPOSSIBLE!You should get to the point where anyone else would quit, and you’re not gonna stop there. NO! What are you waiting for? … DO IT! Just… DO IT! Yes you can! Just do it! If you’re tired of starting over, stop. giving. up.",
			"What the fuck did you just fucking say about me, you little bitch? I’ll have you know I graduated top of my class in the Navy Seals, and I’ve been involved in numerous secret raids on Al-Quaeda, and I have over 300 confirmed kills. I am trained in gorilla warfare and I’m the top sniper in the entire US armed forces. You are nothing to me but just another target. I will wipe you the fuck out with precision the likes of which has never been seen before on this Earth, mark my fucking words. You think you can get away with saying that shit to me over the Internet? Think again, fucker. As we speak I am contacting my secret network of spies across the USA and your IP is being traced right now so you better prepare for the storm, maggot. The storm that wipes out the pathetic little thing you call your life. You’re fucking dead, kid. I can be anywhere, anytime, and I can kill you in over seven hundred ways, and that’s just with my bare hands. Not only am I extensively trained in unarmed combat, but I have access to the entire arsenal of the United States Marine Corps and I will use it to its full extent to wipe your miserable ass off the face of the continent, you little shit. If only you could have known what unholy retribution your little “clever” comment was about to bring down upon you, maybe you would have held your fucking tongue. But you couldn’t, you didn’t, and now you’re paying the price, you goddamn idiot. I will shit fury all over you and you will drown in it. You’re fucking dead, kiddo.",
			"What in Davy Jones’ locker did ye just bark at me, ye scurvy bilgerat? I’ll have ye know I be the meanest cutthroat on the seven seas, and I’ve led numerous raids on fishing villages, and raped over 300 wenches. I be trained in hit-and-run pillaging and be the deadliest with a pistol of all the captains on the high seas. Ye be nothing to me but another source o’ swag. I’ll have yer guts for garters and keel haul ye like never been done before, hear me true. You think ye can hide behind your newfangled computing device? Think twice on that, scallywag. As we parley I be contacting my secret network o’ pirates across the sea and yer port is being tracked right now so ye better prepare for the typhoon, weevil. The kind o’ monsoon that’ll wipe ye off the map. You’re sharkbait, fool. I can sail anywhere, in any waters, and can kill ye in o’er seven hundred ways, and that be just with me hook and fist. Not only do I be top o’ the line with a cutlass, but I have an entire pirate fleet at my beck and call and I’ll damned sure use it all to wipe yer arse off o’ the world, ye dog. If only ye had had the foresight to know what devilish wrath your jibe was about to incur, ye might have belayed the comment. But ye couldn’t, ye didn’t, and now ye’ll pay the ultimate toll, you buffoon. I’ll shit fury all over ye and ye’ll drown in the depths o’ it. You’re fish food now, lad.",
			"Wot the fok did ye just say 2 me m8? i dropped out of newcastle primary skool im the sickest bloke ull ever meet & ive nicked ova 300 chocolate globbernaughts frum tha corner shop. im trained in street fitin’ & im the strongest foker in tha entire newcastle gym. yer nothin to me but a cheeky lil bellend w/ a fit mum & fakebling",
			"helo my name is dongerino pasterino ヽ༼ຈل͜ຈ༽ﾉ, i am 69 year old donger from imaqtmeatloaf’s stream . 420 years ago i was kidnapped and put into a donger concentration camp for 9001 years. 1 year ago, imaqtlasagne and imaqtpie invaded the camp and rescued me. now i work as teacherino, passing down the wisdom of ( ͡° ͜ʖ ͡°) to young dongers.",
			"Gr8 b8, m8. I rel8, str8 appreci8, and congratul8. I r8 this b8 an 8/8. Plz no h8, I’m str8 ir8. Cre8 more, can’t w8. We should convers8, I won’t ber8, my number is 8888888, ask for N8. No calls l8 or out of st8. If on a d8, ask K8 to loc8. Even with a full pl8, I always have time to communic8 so don’t hesit8",
			"˙ʇı ןןɐɔ noʎ ɹǝʌǝʇɐɥʍ ɹo ,ɐʇǝq, pǝɹǝpısuoɔ buıǝq ɟo ʞɔıs ɯ,ı ˙ʇı ʇnoqɐ ʎɹɔ oʇ ǝɯ oʇ ʞןɐʇ ʎןuo puɐ ‘ʇıɥs ǝʞıן ɯǝɥʇ ʇɐǝɹʇ oɥʍ sʎnb bɐqǝɥɔnop ɹǝʇɟɐ ob sʎɐʍןɐ sןɹıb ǝsǝɥʇ puǝ ǝɥʇ uı ˙ʎpɐן,ɯ ɹoɟ buıɥʇʎuɐ op pןnoʍ puɐ ‘qoظ ǝɔıu ɐ ʞɹoʍ ‘ʎnb ǝɔıu ɐ ɯ,ı ˙ǝuoz puǝıɹɟ ǝɥʇ uı ʇnd buıǝq sʎɐʍןɐ ı ɯɐ ʎɥʍ",
			"Whenever I get a package of plain M&Ms, I make it my duty to continue the strength and robustness of the candy as a species. To this end, I hold M&M duels. Taking two candies between my thumb and forefinger, I apply pressure, squeezing them together until one of them cracks and splinters. That is the “loser,” and I eat the inferior one immediately. The winner gets to go another round. I have found that, in general, the brown and red M&Ms are tougher, and the newer blue ones are genetically inferior. I have hypothesized that the blue M&Ms as a race cannot survive long in the intense theater of competition that is the modern candy and snack-food world. Occasionally I will get a mutation, a candy that is misshapen, or pointier, or flatter than the rest. Almost invariably this proves to be a weakness, but on very rare occasions it gives the candy extra strength. In this way, the species continues to adapt to its environment. When I reach the end of the pack, I am left with one M&M, the strongest of the herd. Since it would make no sense to eat this one as well, I pack it neatly in an envelope and send it to M&M Mars, A Division of Mars, Inc., Hackettstown, NJ 17840-1503 U.S.A., along with a 3×5 card reading, “Please use this M&M for breeding purposes.” This week they wrote back to thank me, and sent me a coupon for a free 1/2 pound bag of plain M&Ms. I consider this “grant money.” I have set aside the weekend for a grand tournament. From a field of hundreds, we will discover the True Champion. There can be only one.",
			"That’s it, I’m done. Fuck this chat. It’s devolved into a mass of retarded copy pastes and face spam. The quality of twitch chat has been declining for a while, but this is the last straw. That’s it. I’m done. I’m uninstalling the internet, chopping off my dick and moving to fucking Antarctica, at least the bacteria there will be fucking smarter discourse",
			"ʜᴇʟʟᴏ ᴄʜᴀᴛ ɪ ᴀᴍ ғᴀᴍᴏᴜs ғᴀsᴄɪsᴛ ʟᴇᴀᴅᴇʀ, ᴀᴅᴏʟғ ʜɪᴛʟᴇʀɪɴᴏ. ᴡᴇ ᴡᴏᴜʟᴅ ʟɪᴋᴇ ʏᴏᴜ ᴀɴᴅ ɴᴀᴢɪ ᴍᴏᴅs ᴛᴏ ᴘᴀʀᴛɪᴄɪᴘᴀᴛᴇ ɪɴ ᴏᴜʀ ɴᴇᴡ ᴘʀᴏᴘᴀɢᴀɴᴅᴀ ғɪʟᴍ “sɪᴇɢ ʜᴇɪʟ ʟɪғᴇsᴛʏʟᴇ” ʏᴏᴜ ᴡᴏᴜʟᴅ ʀᴀɪsᴇ ʏᴏᴜʀ ᴅᴏɴɢᴇʀs ᴀɴᴅ ɴᴀᴢɪ ᴍᴏᴅs sᴀʏ ɴᴏ ᴘᴀsᴛᴇʀɪɴᴏ ᴀɴᴅ ʙᴀɴʜᴀᴍᴍᴇʀ.",
			"Hello Alkaizer, this is Hollywood director and producer Eddy Pasterino. We would like you and fowtini to star in our new movie: Naked Skorñorita. You will go the the inn and see fowtini lying in Leah’s bed and she will want your Skorn but you say “No Skornerrino” and topdeck her. Pls no hastalapasta baberino.",
			"Has anyone really been far even as decided to use even go want to do look more like?",
			"ICH WAS UNO LITTLE BOY RUNERINO FROM D STEAM POLIS. MEH NO WANTERINO TO WENT JAILERINO MEH CREATERINO MY FIRST GUNERINO. UNO DAY MEH MEAT TANJA KRALJ IT TOLD MEH TO KILLERINO D STEAM POLIS. MEH THAT DONE. IT MEH SAVE. NOW ICH AM BEST SHOOTERINO IN NIGGERIA. THAN UNO DAI MI TURTL RUNNERINO AVAY TO BRASIL SO ICH MUST CHATCHERINO HER. MUY FUTER FUND MEH IN BRASIL ANDT WE STOLE A BIKERINO AND DRIVERINO TO MEXICO. THERE MUY LUYFERINO CHANGERED AND ICH GET MY CHOMPUTER FROMERINO TANJA KRALJ.",
			"hi mi name es giorgio i woerk in potatoe faktory and since mi padre died in a donkey waggon accident i leav mi wife and ugli daughter to become a pro leagueue of leyendaerio player, everydai i watch rainamndio. i just wante to sai thank you veriyi much rauinmanio i improvd from bronce 5 to wood 7 in just 6 months. plz no copato pasterato dis is onli my life. i ALso killed mi dog. Sorry fo mi bad englando im not NA",
			"I sexually Identify as an Attack Helicopter. Ever since I was a boy I dreamed of soaring over the oilfields dropping hot sticky loads on disgusting foreigners. People say to me that a person being a helicopter is Impossible and I’m fucking retarded but I don’t care, I’m beautiful. I’m having a plastic surgeon install rotary blades, 30 mm cannons and AMG-114 Hellfire missiles on my body. From now on I want you guys to call me “Apache” and respect my right to kill from above and kill needlessly. If you can’t accept me you’re a heliphobe and need to check your vehicle privilege. Thank you for being so understanding.",
			"I can no longer resist the pizza. I open the box and unzip my pants with my other hand. As I penetrate the gooey cheese, I moan in ecstacy. The mushrooms and Italian sausage are rough, but the sauce is deliciously soothing. I blow my load in seconds. As you leave the bathroom, I exit through the front door…",
			"Hey Faggots, My name is John, and I hate every single one of you. All of you are fat, retarded, no-lifes who spend every second of their day looking at stupid ass pictures. You are everything bad in the world. Honestly, have any of you ever gotten any pussy? I mean, I guess it’s fun making fun of people because of your own insecurities, but you all take to a whole new level. This is even worse than jerking off to pictures on facebook. Don’t be a stranger. Just hit me with your best shot. I’m pretty much perfect. I was captain of the football team, and starter on my basketball team. What sports do you play, other than “jack off to naked drawn Japanese people”? I also get straight A’s, and have a banging hot girlfriend (She just blew me; Shit was SO cash). You are all faggots who should just kill yourselves. Thanks for listening. Pic Related: It’s me and my bitch",
			"“wtf his ult did like 3k damage how is that legit” – leonardo da vinci 1496, founder of the Illuminati",
			"Hello twitch chat. This is michaels mother speaking. Please stop the spam in the chat. I can’t read the amazing conversations that you are having about my son. Thanks. Don’t copy and paste this to spam more or I will tell Michael to ban you all.",
			"Why am I always being put in the friend zone. I’m a nice guy, work a nice job, and would do anything for m’lady. In the end these girls always go after DOUCHEBAG guys who treat them like shit, and only talk to me to cry about it. I’m sick of being considered ‘beta’ or whatever you call it.",
			"Hello. I am a 15 year old Rhinoceros. The only problem is that my horn on my head is soft and limp. As you may know this is very devastating to a rhino like myself. If there are any rhinos out there that can help me with my problem it would be appreciated. Please dont copy paste this. This is my story."
	};

	public CopyPasta(String command, String description, String usage)
	{
		super(command, description, usage);
	}

	@Override
	public void trigger(MessageParams p_messageParams)
	{
		try {
			p_messageParams.getTextChannel().sendMessage(copypastas[RandomGen.rndNm(copypastas.length)]).complete();
		} catch(Exception e) {
			System.out.println(e.getMessage());
		}
	}
}
